name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        kind: ["linux", "windows", "macos"]
        include:
          - kind: linux
            os: ubuntu-latest
            lib: "libspeexdsp.a"
          - kind: windows
            os: windows-latest
            lib: "speexdsp.lib"
          - kind: macos
            os: macos-latest
            lib: "libspeexdsp.a"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

      - name: Package
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p binaries
          cp ${{runner.workspace}}/build/Release/${{matrix.lib}} binaries/
      - name: Package
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p binaries
          cp ${{runner.workspace}}/build/${{matrix.lib}} binaries/

      - uses: actions/upload-artifact@v2
        with:
          name: speexdsp-${{ matrix.kind }}
          path: binaries/
